### ISSUE TITLE
Unable to Launch Microcks

### ISSUE THREAD

**Issue by collabnix** [microcks/microcks-docker-desktop-extension#1]
I tried building the extension and installing it. Even though extension worked perfectly but unable to see any activity when I clicked over the "Launch" button. 

<img width="1031" alt="Screenshot 2022-06-16 at 11 04 56 AM" src="https://user-images.githubusercontent.com/34368930/173998822-13d19b4b-dcbf-40ee-8302-1ab3519a5cdc.png">

**Comment by lbroudoux** [comment]
Yeah ... be patient ;-) we just have started dev ;-)

**Comment by collabnix** [comment]
Sure. Will keep eye on this.
