### ISSUE TITLE
Message: "Port is already allocated" thrown when a "network not found" exception is generated

### ISSUE THREAD

**Issue by amseager** [microcks/microcks-docker-desktop-extension#20]
### Describe the bug

After installing Microcks docker extension, it can be launched b/c of the port issue no matter what offset you set in the config.

`Port is already allocated. Please use a different port by changing the port offset in the settings dialog.`

### Microcks version or git rev

0.2.0

### Install method (`docker-compose`, `helm chart`, `operator`, `docker-desktop extension`,...)

From the docker extension marketplace

**Comment by amseager** [comment]
Hello @hguerrero, here you go https://gist.github.com/amseager/9195e106a9ae7a9270a688febad655ff

Found in logs that `network microcks-extension-network not found`, created it manually from console, and looks like it solved the problem.

So, 2 small issues - the network is not created automatically, and the error message is misleading in this case

**Comment by hguerrero** [comment]
Thank you @amseager 

As I expected, it is another exception caught by the same code that throws a misleading message. 

Let me check and work on this. I just wanted to let you know that I update the title of this issue for reference.
