### ISSUE TITLE
Automatically refresh APIs 

### ISSUE THREAD

**Issue by hguerrero** [microcks/microcks-docker-desktop-extension#25]
### Reason/Context

When adding APIs via the Microcks UI, we need a way to refresh the APIs on Docker UI

### Description

The APIs in the Docker UI should reflect the changes made in the Microcks UI

### Implementation ideas

There are a couple options:

- Poll the services every X seconds
- Publish and event
- Websockets

**Comment by hguerrero** [comment]
@lbroudoux is there any kind of event or webhook in microcks for newly created services?

**Comment by lbroudoux** [comment]
Now we've got something! When using `microcks-uber` with version starting `1.8.1`, these events are published on a WS endpoint that is located on the main webapp component. We could use that to get this information!

See https://microcks.io/blog/microcks-1.8.1-release/#uberall-in-one-architecture-simplification
