### ISSUE TITLE
Add links to report issues

### ISSUE THREAD

**Issue by hguerrero** [microcks/microcks-docker-desktop-extension#29]
### Reason/Context

Make it easy for users to report issues

### Description

In case of any issue, make it easier for users to report by directing them to github issues, and if possible, prefill with the information of the current system.

### Implementation ideas

- Just add a link to the main page (similar to delete microcks)
- Try to add a handler to show the message when we detect errors.

**Comment by lbroudoux** [comment]
Has that one been included in `0.3.0` or not yet?

**Comment by hguerrero** [comment]
No, there is no current definition how the Link should look like or where should it be located 😕 

I am open to suggestions 😃

**Comment by lbroudoux** [comment]
Could there be an addition in the Footer just after the date and the copyright notice?
Something like:

> For any suggestions, feature requests and issue, head over the [project's GitHub Issues tracker](https://github.com/microcks/microcks-docker-desktop-extension/issues/).
