### ISSUE TITLE
Unable to launch extension

### ISSUE THREAD

**Issue by andrebiegel** [microcks/microcks-docker-desktop-extension#9]
hey i installed the extension through the marketplace and want to launch it .. but the wheel keeps spinning 
![grafik](https://user-images.githubusercontent.com/18468602/226554391-58b739ee-b48c-4551-a474-e7de0ed1d814.png)
any idee how to find out what is not working ? 
docker desktop version 4.17.1

**Comment by hguerrero** [comment]
Hi @andrebiegel 

I did a new install using 4.17 (need to update to the latest), and looks like everything is fine. Usually, the first time it takes some time to start as it is downloading the containers required to run. 

Does it get stuck for more than 10 minutes?

**Comment by andrebiegel** [comment]
yes .. also tested the extension on an complety fresh install of docker desktop 4.19, is there some kind of log where i can see what is going on ?

**Comment by hguerrero** [comment]
@andrebiegel  yes, you can enable the debug traces in the extension or you can also change the settings to show the containers running the extension

Test and debug: https://docs.docker.com/desktop/extensions-sdk/dev/test-debug/

Show containers: https://docs.docker.com/desktop/extensions-sdk/dev/test-debug/#show-the-extension-containers

**Comment by andrebiegel** [comment]
`mongostatus So {exists: true, isRunning: true, mappedPort: 0}exists: trueisRunning: truemappedPort: 0[[Prototype]]: Object
App.tsx:285 postmanstatus So {exists: true, isRunning: true, mappedPort: 0}exists: trueisRunning: truemappedPort: 0[[Prototype]]: Object
App.tsx:312 appstatus So {exists: false, isRunning: false, mappedPort: 0}
App.tsx:355 Creating  microcks
App.tsx:658 [microcks] docker: Invalid hostPort: NaN.
App.tsx:658 [microcks] See 'docker run --help'.
App.tsx:666 [microcks] onClose with exit code 125`

Thats the logs in the chrome dev console ..

**Comment by lbroudoux** [comment]
Hi @andrebiegel,

I agree that a warning message would be nice on that specific bootstrap issue. Don't know if you see it but you have the ability to change the used ports within the settings pane in case you're facing conflicts. 

Let us know if that solves your issue. 

Thanks 🙏

**Comment by hguerrero** [comment]
I was able to reproduce the issue. I will work on a patch to handle this issue.

**Comment by ggirard07** [comment]
Not sure I m hitting the same issue, but it results in same behavior that extension startup just keep spinning.
In my case, I already added an offset on the ports in settings before to try to run the extension.
Configured the debuger, here are the relevant errors I got:
```
Creating  microcks
[microcks-postman] 27dafcff537c3d7c91b2b67b9ca1cda12b7b3629d7d139050178e21a4913dc56
[microcks-mongodb] acb9708d1c5102df2c28012db4f0785249ba40959e1c3a653efce162259cbf47
[microcks] 49b6b55662e00a16532674351319344b3cb36fdc45db7cc0cd497c4f2a285b37
[microcks-postman] docker: Error response from daemon: network microcks-extension-network not found.
[microcks-mongodb] docker: Error response from daemon: network microcks-extension-network not found.
[microcks-postman] onClose with exit code 125
[microcks-mongodb] onClose with exit code 125
[microcks] docker: Error response from daemon: network microcks-extension-network not found.
[microcks] onClose with exit code 125
```
